### ISSUE TITLE
Make unit tests and `gen_log_guide.ts` pull example log lines from a common resource

### ISSUE THREAD

**Issue by xiashtra** [OverlayPlugin/cactbot#125]
### Feature(s) Requested

Per @valarnin comment on #121 :

> the unit tests and the gen_log_guide.ts files should pull from a common resource somewhere, rather than duplicating these lines

**Comment by wexxlee** [comment]
It probably makes sense to land this before doing unit tests for the log splitter, since that unit test could (should) pull from these as well.  

In terms of how to implement, would it make sense to:
 - throw all the lines into a dummy log file, grouped by type
  - have `gen_log_guide` read/parse the file by line type
   - have `test/unittests/netregex_test` do the same thing
   - have `test/unittest/regex_test` use the same logic in `gen_log_guide` to convert the lines to ACT-style log lines and then parse by type?
   
If we took this approach, I think we'd probably still need to keep all the hardcoded `assert.equal` stuff in the unit test files, unless anyone can think of a good way around that?

**Comment by valarnin** [comment]
I don't see any additional value in having the log lines in a `*.log` file that needs parsed out, as opposed to being stored as a properly formed const var in something like `resources/example_log_lines.ts`, by just moving the existing structure in `gen_log_guide.ts` out to a new file.

**Comment by wexxlee** [comment]
In theory, I think the benefit of having it in a `*.log` file would be if we also wanted to use the file to unit test splitter/filter/anonymizer, as I alluded to in #109.

But the more I've been thinking about that, I'm not sure how useful that unit test will be.  The regex/netregex unit tests already take care of line parsing, so the only portion left to unit test is whether the code is parsing lines correctly based on `netlog_defs` properties and the internal processing logic in `splitter.ts`.  I'm not sure what a unit test would encompass beyond simply duplicating the existing logic in `splitter.ts`, and that doesn't seem like much added value.  So yeah, maybe a const is the way to go here.
