### ISSUE TITLE
Missing translation for resources/example_log_lines.ts ?

### ISSUE THREAD

**Issue by mooondark** [OverlayPlugin/cactbot#157]
Hi there,
I don't think we should translate the examples lines, is it possible to remove it from the [missing translation page](https://overlayplugin.github.io/cactbot/util/coverage/missing_translations_fr.html) ?

Regards,
moon.

**Comment by valarnin** [comment]
I sort-of agree, and sort-of disagree here.

For most of the log lines, they don't need entries for other languages.

Some log lines may benefit from having other languages, e.g. `Map`, `StartsUsing`, or `Ability`, though I can't say for certain as I don't do any translations, nor do I write triggers against non-english log files.

Additionally, it may be good to note somewhere or somehow what documents still need translations, though that's only tangentially related to this issue. (e.g. there is no `/docs/ko-KR/LogGuide.md`)

Either way, until #138 and #139 are merged, we can't really flag these as not needing translation since they're being moved to a new file as part of those PRs.
