### ISSUE TITLE
make_timeline ignores empty-name combatants

### ISSUE THREAD

**Issue by wexxlee** [OverlayPlugin/cactbot#18]
Initial discussion in quisquous/cactbot#5943.

`make_timeline` is ignoring abilities from combatants with empty names because `ignoredCombatants` includes an empty string ('') as a combatant to be ignored.  Removing that element from the array fixes the issue.  But I'm not sure whether that's something we should do, or if there's history on why we ignore empty-name combatants when making a timeline.

In the case of the Aloalo log (and I imagine most if not all cases where an ability is used by an empty-name combatant), the ability used also does not have a name, so `make_timeline` will only generate "--sync--" lines anyway.  I think there's a couple options:

1. **Leave as-is**.  On the off-chance an empty-name combatant uses an ability that might be relevant for timelines or triggers, we'll let whoever is coding it figure out what's going on and manually add lines on the (remote) off-chance they are needed.
2. **Add empty-name-combatant timeline entries, but only if a named ability is used.**  Minor improvement to the above that could catch a future edge case where we'd want the timeline entry.  Seems low-probability, but it's arguably better than the current state.
3. **Include abilities from empty-name combatants.** This will eliminate the gap, but leaves more work for those creating timelines to identify and remove these syncs if not useful.

I think I lean toward  option 2, but I don't feel very strongly about it.  If no one else has an opinion, that's probably what I'll do.
(cc: @JLGarber )

**Comment by JLGarber** [comment]
Well, [that has been there since the beginning](https://github.com/OverlayPlugin/cactbot/blame/3f8e28c0be3511ee3767e7f64fcc00951ef0dea0/util/make_timeline.py#L32). I don't think we need to worry too much about what was originally intended given that it's just sort of always been that way.

I think you're right that option 2 is a good compromise. There's the potential for future content that would be more understandable under option 3, but I think if there's a comment in-line explaining the rationale, that should be good enough. (Plus, there will be the PR linking to this issue for further explanation, so it should be simple enough for future timeline work to reference this.)
