### ISSUE TITLE
Anytime I get an alert through Raidboss Alerts and Timeline my audio in game cuts out

### ISSUE THREAD

**Issue by heyimtra** [OverlayPlugin/cactbot#457]
Anytime I get a raid audio alert with raid boss alerts and timeline, my game audio completely cuts out - but the rest of the audio on my PC is fine. I am not sure what is causing this as it was fine up until yesterday. I tried to look every where online for a remedy but I came across nothing and was hoping I would find some insight here. Thanks!

**Comment by jacob-keller** [comment]
What renders cactbot for you? The standard overlay plugin with ACT? something like browsingway with IINACT? or some other plugin in game?

This sounds like whatever is rendering your audio is coming from a plugin that overrides the game audio rather than sending audio as a separate source?

Can you try loading the cactbot UI in a webrowser directly, disabling whatever is normally rendering it and see if you get the same issue?

**Comment by xiashtra** [comment]
Closing due to lack of response from the original submitter.
